/* Generated by Cython 0.29.28 */

#ifndef __PYX_HAVE__parse_conf
#define __PYX_HAVE__parse_conf

#include "Python.h"

#ifndef __PYX_HAVE_API__parse_conf

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyObject *parse_conf(PyObject *, int);

#endif /* !__PYX_HAVE_API__parse_conf */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initparse_conf(void);
#else
PyMODINIT_FUNC PyInit_parse_conf(void);
#endif

#endif /* !__PYX_HAVE__parse_conf */
